### ISSUE TITLE
jinja2.exceptions.TemplateNotFound: encoded_python.tpl

### ISSUE THREAD

**Issue by actforjason** [ttung/nbencdec#3]
`nbencdec encode attention_model_validation_experiments.ipynb han.py`

> Traceback (most recent call last):
  File "C:\Users\Jason\miniconda3\Scripts\nbencdec-script.py", line 33, in <module>
    sys.exit(load_entry_point('nbencdec', 'console_scripts', 'nbencdec')())
  File "f:\nlp_projects\nbencdec\nbencdec\cli\commands.py", line 124, in main
    args.command(args)
  File "f:\nlp_projects\nbencdec\nbencdec\cli\commands.py", line 97, in encode
    encoded, _ = encoder.from_file(input_fh)
  File "C:\Users\Jason\miniconda3\lib\site-packages\nbconvert\exporters\exporter.py", line 199, in from_file
    return self.from_notebook_node(nbformat.read(file_stream, as_version=4), resources=resources, **kw)
  File "C:\Users\Jason\miniconda3\lib\site-packages\nbconvert\exporters\templateexporter.py", line 384, in from_notebook_node
    output = self.template.render(nb=nb_copy, resources=resources)
  File "C:\Users\Jason\miniconda3\lib\site-packages\nbconvert\exporters\templateexporter.py", line 148, in template
    self._template_cached = self._load_template()
  File "C:\Users\Jason\miniconda3\lib\site-packages\nbconvert\exporters\templateexporter.py", line 355, in _load_template
    return self.environment.get_template(template_file)
  File "C:\Users\Jason\miniconda3\lib\site-packages\jinja2\environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "C:\Users\Jason\miniconda3\lib\site-packages\jinja2\environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "C:\Users\Jason\miniconda3\lib\site-packages\jinja2\loaders.py", line 429, in load
    raise TemplateNotFound(name)
jinja2.exceptions.TemplateNotFound: encoded_python.tpl

**Comment by ttung** [comment]
Which version of `nbconvert` do you have installed?

**Comment by actforjason** [comment]
`nbconvert               6.0.7`

**Comment by ttung** [comment]
Hm... are you using nbencdec 0.0.10?  That should have the fix.

**Comment by actforjason** [comment]
`nbencdec 0.0.2`

**Comment by ttung** [comment]
Yeah, please upgrade to 0.0.10!  Thanks.

**Comment by actforjason** [comment]
Oh no, `nbencdec                0.0.10`,   I mistook it for the release.

**Comment by actforjason** [comment]
![image](https://user-images.githubusercontent.com/57058325/114348925-cc034500-9b99-11eb-89b3-996de610a4a4.png)
